- name: Download Cloudwatch
  get_url:
    url: https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dest: /home/ansible
- name: Extract Cloudwatch
  command: sudo dpkg -i -E /home/ansible/amazon-cloudwatch-agent.deb
- name: Upload Cloudwatch Config
  copy:
    src: /home/ansible/cloudwatch_agent/config.json
    dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
  notify: Start Cloudwatch